import os
import sys
from fontTools.ttLib import TTFont

def convert_to_woff2(input_path, output_path=None):
    '''Convert a TTF/OTF font to WOFF2 format.'''
    if not output_path:
        base, _ = os.path.splitext(input_path)
        output_path = base + ".woff2"
    
    print(f"Loading font: {input_path}")
    font = TTFont(input_path)
    print(f"Compressing to WOFF2: {output_path}")
    font.flavor = 'woff2'
    font.save(output_path)
    return output_path

def generate_css_template(font_path, font_family=None):
    '''Generate a CSS @font-face template.'''
    filename = os.path.basename(font_path)
    if not font_family:
        font_family = os.path.splitext(filename)[0]
    
    css_content = f"""/* Webfont CSS Template generated by OpenCC Font Generator */

@font-face {{
  font-family: '{font_family}';
  src: url('{filename}') format('woff2');
  font-weight: normal;
  font-style: normal;
  font-display: swap;
}}

/* Usage Example:
body {{
  font-family: '{font_family}', sans-serif;
}}
*/
"""
    return css_content

def process_webfont(input_path, output_path=None, font_family=None):
    # 1. 執行轉換
    final_woff2_path = convert_to_woff2(input_path, output_path)
    
    # 2. 產生 CSS
    css_content = generate_css_template(final_woff2_path, font_family)
    
    # 3. 儲存 CSS 檔案 (與 woff2 同目錄)
    output_dir = os.path.dirname(final_woff2_path)
    css_path = os.path.join(output_dir, "fonts.css")
    
    with open(css_path, "w", encoding="utf-8") as f:
        f.write(css_content)
    
    print(f"✅ Webfont created: {final_woff2_path}")
    print(f"✅ CSS template created: {css_path}")
    return final_woff2_path, css_path

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python webfont.py input.ttf [output.woff2] [font-family]")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else None
    family = sys.argv[3] if len(sys.argv) > 3 else None
    
    process_webfont(input_file, output_file, family)
